In [1]:
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt

print('PyTorch 🔥 version')
print(torch.__version__)

PyTorch 🔥 version
1.13.1


In [3]:
scalar = torch.tensor(7)
display(scalar)
scalar.item()

tensor(7)

7

In [9]:
vector = torch.tensor([7, 7])
display(vector, vector.shape, vector.ndim)

for v in vector:
    print(v.item())

tensor([7, 7])

torch.Size([2])

1

7
7


In [17]:
MATRIX = torch.tensor([[7, 7], [57, 57], [37, 37]])
display(MATRIX, MATRIX.shape, MATRIX.ndim)

i = 0
for _ in MATRIX:
    print(MATRIX[i])
    i += 1

tensor([[ 7,  7],
        [57, 57],
        [37, 37]])

torch.Size([3, 2])

2

tensor([7, 7])
tensor([57, 57])
tensor([37, 37])


In [20]:
TENSOR = torch.tensor([[[7, 7], [57, 57], [37, 37]],
                       [[27, 27], [47, 47], [67, 67]]])
display(TENSOR, TENSOR.shape, TENSOR.ndim)

i = 0
for _ in TENSOR:
    print(i, ')', TENSOR[i])
    i += 1

tensor([[[ 7,  7],
         [57, 57],
         [37, 37]],

        [[27, 27],
         [47, 47],
         [67, 67]]])

torch.Size([2, 3, 2])

3

0 ) tensor([[ 7,  7],
        [57, 57],
        [37, 37]])
1 ) tensor([[27, 27],
        [47, 47],
        [67, 67]])
