# Imports

In [1]:
"""
feb13-feb28 = 16
mar1-mar31 = 31
apr1-apr30 = 30
may1-may5 = 5
total = 82 days
"""
import torch
import pandas
import numpy as np
import matplotlib.pyplot as plt

print('PyTorch 🔥 version')
print(torch.__version__)

PyTorch 🔥 version
1.13.1


In [2]:
scalar = torch.tensor(7)
display(scalar)
scalar.item()

tensor(7)

7

In [3]:
vector = torch.tensor([7, 7])
display(vector, vector.shape, vector.ndim)

for v in vector:
    print(v.item())

tensor([7, 7])

torch.Size([2])

1

7
7


In [4]:
MATRIX = torch.tensor([[7, 7], [57, 57], [37, 37]])
display(MATRIX, MATRIX.shape, MATRIX.ndim)

i = 0
for _ in MATRIX:
    print(MATRIX[i])
    i += 1

tensor([[ 7,  7],
        [57, 57],
        [37, 37]])

torch.Size([3, 2])

2

tensor([7, 7])
tensor([57, 57])
tensor([37, 37])


In [5]:
TENSOR = torch.tensor([[[7, 7], [57, 57], [37, 37]],
                       [[27, 27], [47, 47], [67, 67]]])
display(TENSOR, TENSOR.shape, TENSOR.ndim)

i = 0
for _ in TENSOR:
    print(i, ')', TENSOR[i])
    i += 1

tensor([[[ 7,  7],
         [57, 57],
         [37, 37]],

        [[27, 27],
         [47, 47],
         [67, 67]]])

torch.Size([2, 3, 2])

3

0 ) tensor([[ 7,  7],
        [57, 57],
        [37, 37]])
1 ) tensor([[27, 27],
        [47, 47],
        [67, 67]])


# Random Tensors

In [6]:
random_tensor = torch.rand(3, 4)
display(random_tensor, random_tensor.shape, random_tensor.ndim)

tensor([[0.6745, 0.2423, 0.8344, 0.9438],
        [0.1220, 0.0190, 0.8417, 0.5654],
        [0.3838, 0.1697, 0.9087, 0.1172]])

torch.Size([3, 4])

2

In [7]:
# height, width, channels (R, G, B)
random_img_tensor = torch.rand(size=(224, 224, 3))
display(random_img_tensor, random_img_tensor.shape, random_img_tensor.ndim)

tensor([[[0.7143, 0.2370, 0.3268],
         [0.5525, 0.5484, 0.0132],
         [0.5079, 0.2182, 0.8425],
         ...,
         [0.9822, 0.3071, 0.6757],
         [0.8301, 0.5044, 0.4914],
         [0.0490, 0.1079, 0.2456]],

        [[0.0821, 0.6411, 0.5186],
         [0.3848, 0.4866, 0.5085],
         [0.5641, 0.1766, 0.4629],
         ...,
         [0.0880, 0.2415, 0.9200],
         [0.4390, 0.8838, 0.3880],
         [0.8827, 0.2650, 0.8505]],

        [[0.7211, 0.8472, 0.9181],
         [0.5771, 0.0502, 0.4114],
         [0.2819, 0.4559, 0.3352],
         ...,
         [0.8283, 0.1961, 0.6263],
         [0.5310, 0.9627, 0.7602],
         [0.8716, 0.7040, 0.6673]],

        ...,

        [[0.1666, 0.3815, 0.4595],
         [0.4795, 0.5171, 0.2780],
         [0.0747, 0.7619, 0.6647],
         ...,
         [0.4626, 0.2615, 0.1149],
         [0.4143, 0.9380, 0.4668],
         [0.6972, 0.1551, 0.4553]],

        [[0.1903, 0.0871, 0.0017],
         [0.4172, 0.1036, 0.2182],
         [0.

torch.Size([224, 224, 3])

3

# Zeros and Ones Tensors

In [9]:
zeros = torch.zeros(size=(3, 4))
display(zeros, zeros.shape, zeros.ndim, zeros.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.Size([3, 4])

2

torch.float32

In [11]:
ones = torch.ones(size=(3, 4))
display(ones, ones.shape, ones.ndim, ones.dtype)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

torch.Size([3, 4])

2

torch.float32

# torch arange & like

In [14]:
torch.arange(start=0, end=11, step=2)

tensor([ 0,  2,  4,  6,  8, 10])

In [16]:
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
torch.zeros_like(input=one_to_ten)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor Datatypes

In [22]:
float_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None,
    device=None,  # CPU, GPU, CUDA, TPU, etc.
    requires_grad=False # whether to track gradient
)
float_tensor.dtype

torch.float32

In [23]:
float_tensor.type(torch.half)

tensor([3., 6., 9.], dtype=torch.float16)

In [24]:
float_tensor.type(torch.float16)

tensor([3., 6., 9.], dtype=torch.float16)

# Tensor Operations

In [25]:
float_tensor + 10

tensor([13., 16., 19.])

In [26]:
float_tensor * 10

tensor([30., 60., 90.])

In [27]:
float_tensor * float_tensor

tensor([ 9., 36., 81.])

# Matrix Multiplication

In [30]:
%%time
m1 = torch.tensor([[1, 2], [3, 4]])
m2 = torch.tensor([[5, 6], [7, 8]])
torch.matmul(m1, m2)

CPU times: user 206 µs, sys: 462 µs, total: 668 µs
Wall time: 979 µs


tensor([[19, 22],
        [43, 50]])

In [33]:
%%time
mm1 = torch.matmul(torch.rand(5, 3), torch.rand(3, 2))
display(mm1, mm1.shape, mm1.ndim, mm1.dtype)

tensor([[1.0827, 0.8118],
        [1.2031, 1.3135],
        [0.4622, 0.5003],
        [0.7931, 0.6606],
        [0.8844, 0.6880]])

torch.Size([5, 2])

2

torch.float32

CPU times: user 4.73 ms, sys: 2.15 ms, total: 6.88 ms
Wall time: 5.42 ms


In [34]:
%%time
mm1 = torch.matmul(torch.rand(5, 3000), torch.rand(3000, 2))
display(mm1, mm1.shape, mm1.ndim, mm1.dtype)

tensor([[764.2687, 761.3394],
        [730.5199, 741.3401],
        [749.5496, 756.8575],
        [744.4789, 755.5326],
        [758.1427, 764.2729]])

torch.Size([5, 2])

2

torch.float32

CPU times: user 4.75 ms, sys: 2.32 ms, total: 7.07 ms
Wall time: 22.2 ms


# Positional Maximum and Minimum

In [38]:
t1 = torch.tensor([1111, 250, 3, 4, 5])

In [39]:
t1.argmin()

tensor(2)

In [40]:
t1.argmax()

tensor(0)

# Reshaping, stacking, squeezing and unsqueezing

In [44]:
t = torch.arange(1, 11)
display(t, t.shape, t.ndim)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

torch.Size([10])

1

torch.int64

In [47]:
t_reshaped = t.reshape(2, 5)
display(t_reshaped, t_reshaped.shape, t_reshaped.ndim)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

torch.Size([2, 5])

2

In [49]:
t_reshape2 = t.reshape(1, 10)
display(t_reshape2, t_reshape2.shape, t_reshape2.ndim)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

torch.Size([1, 10])

2

In [51]:
t_reshape2.squeeze()

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
x_orig = torch.rand(size=(224,224, 3))
display(x_orig, x_orig.shape, x_orig.ndim)

tensor([[[0.0890, 0.4023, 0.9144],
         [0.6120, 0.3706, 0.2183],
         [0.0293, 0.7928, 0.8488],
         ...,
         [0.1196, 0.1516, 0.0376],
         [0.2629, 0.2680, 0.4966],
         [0.7515, 0.1704, 0.7938]],

        [[0.3795, 0.6411, 0.1323],
         [0.9189, 0.1112, 0.1557],
         [0.6789, 0.5548, 0.7176],
         ...,
         [0.3339, 0.5412, 0.4045],
         [0.3331, 0.2402, 0.0535],
         [0.3015, 0.7477, 0.0642]],

        [[0.5389, 0.9366, 0.2916],
         [0.9186, 0.9649, 0.6260],
         [0.7941, 0.8346, 0.9557],
         ...,
         [0.8457, 0.1638, 0.0897],
         [0.5002, 0.9837, 0.8372],
         [0.9522, 0.2287, 0.0648]],

        ...,

        [[0.6379, 0.3044, 0.6695],
         [0.0664, 0.4925, 0.9378],
         [0.3165, 0.0678, 0.6047],
         ...,
         [0.1843, 0.2295, 0.2132],
         [0.4629, 0.2301, 0.0128],
         [0.1460, 0.6727, 0.4257]],

        [[0.3790, 0.3493, 0.2460],
         [0.1907, 0.7712, 0.3883],
         [0.

torch.Size([224, 224, 3])

3

In [53]:
x_permuted = x_orig.permute(2, 0, 1)
display(x_permuted, x_permuted.shape, x_permuted.ndim)

tensor([[[0.0890, 0.6120, 0.0293,  ..., 0.1196, 0.2629, 0.7515],
         [0.3795, 0.9189, 0.6789,  ..., 0.3339, 0.3331, 0.3015],
         [0.5389, 0.9186, 0.7941,  ..., 0.8457, 0.5002, 0.9522],
         ...,
         [0.6379, 0.0664, 0.3165,  ..., 0.1843, 0.4629, 0.1460],
         [0.3790, 0.1907, 0.0929,  ..., 0.1063, 0.6138, 0.2604],
         [0.8740, 0.0929, 0.3498,  ..., 0.7044, 0.7247, 0.6333]],

        [[0.4023, 0.3706, 0.7928,  ..., 0.1516, 0.2680, 0.1704],
         [0.6411, 0.1112, 0.5548,  ..., 0.5412, 0.2402, 0.7477],
         [0.9366, 0.9649, 0.8346,  ..., 0.1638, 0.9837, 0.2287],
         ...,
         [0.3044, 0.4925, 0.0678,  ..., 0.2295, 0.2301, 0.6727],
         [0.3493, 0.7712, 0.2582,  ..., 0.1607, 0.3932, 0.3585],
         [0.8454, 0.6645, 0.6923,  ..., 0.6340, 0.1019, 0.2380]],

        [[0.9144, 0.2183, 0.8488,  ..., 0.0376, 0.4966, 0.7938],
         [0.1323, 0.1557, 0.7176,  ..., 0.4045, 0.0535, 0.0642],
         [0.2916, 0.6260, 0.9557,  ..., 0.0897, 0.8372, 0.

torch.Size([3, 224, 224])

3

In [54]:
torch.cuda.is_available()

False